ALTER TABLE `former22_session`
ADD COLUMN `id` INT(10) NOT NULL AUTO_INCREMENT FIRST,
ADD COLUMN `sessionFk` INT(11) NOT NULL AFTER `sessionLocation`,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`id`) USING BTREE;
