ALTER TABLE `former22_inscription`
ADD COLUMN `id` INT(10) NOT NULL AUTO_INCREMENT FIRST,
ADD COLUMN `inscriptionFk` INT(11) NOT NULL AFTER `remark`,
DROP PRIMARY KEY,
ADD PRIMARY KEY (`id`) USING BTREE;
