ALTER TABLE `former22_user`
	ADD COLUMN `id` INT(10) NOT NULL AUTO_INCREMENT FIRST,
	ADD COLUMN `userFk` INT(10) NOT NULL AFTER `cfNumber`,
	DROP PRIMARY KEY,
	ADD PRIMARY KEY (`id`) USING BTREE,
	ADD CONSTRAINT `FK_former22_user_claro_user` FOREIGN KEY (`userFk`) REFERENCES `claro_user` (`id`) ON UPDATE NO ACTION ON DELETE NO ACTION;
