components:
  schemas:
    Course:
      type: object
      required:
        - id
        - code
        - name
        - creationDate
      properties:
        id:
          type: string
          description: L'UUID de la formation, généré automatiquement par Claroline (e.g. 01c292b5-43a4-4c59-9619-33a8309cdbf0)
        code:
          type: string
          description: Le code de la formation, saisi par le CEP dans Claroline (e.g. ACCESS)
        name:
          type: string
          description: 'Le nom complet de la formation (e.g. Access : bien débuter avec les bases de données)'
        isActive:
          type: boolean
          description: Si la formation est active (true/false)
        creationDate:
          type: string
          description: La date de création (en ISO) de la formation (e.g. 2021-05-31T14:33:08.000Z)
        typeStage:
          type: string
          description: Le type stage de la formation ('Attestation', 'Certificat', 'Autre')
        teachingMethod:
          type: string
          description: La méthode d'enseignement de la formation ('Présentiel', 'Distanciel', 'E-learning', 'Mixte/Blended')
        codeCategory:
          type: string
          description: Le code catégorie de la formation ('Catalogue', 'FSM', 'PS', 'CIE', 'CAS')
        isCertifying:
          type: boolean
          description: Si la formation est certifiante - si typeStage === 'Certificat' (true/false)
        isRecurrent:
          type: boolean
          description: Si la formation est cyclique, répétée dans le temps, comme Mesure d'Urgence (true/false)
        durationHours:
          type: string
          description: La durée en heures de chaque session, saisi au niveau de la formation (e.g. 11.25)
        summary:
          type: string
          description: Résumé (description courte) de la formation
        # maxParticipants:
        #   type: string
        #   description: La limite de nombre de participants par session
      example:
        id: '01c292b5-43a4-4c59-9619-33a8309cdbf0'
        code: 'ACCESS'
        name: 'Access : bien débuter avec les bases de données'
        isActive: true
        typeStage: 'Certificat'
        teachingMethod: 'Mixte/Blended'
        codeCategory: 'Catalogue'
        isCertifying: true
        isRecurrent: true
        durationHours: 11.25
        creationDate: '2021-05-31T14:33:08.000Z'
        summary: 'Dans cette formation vous découvrirez la construction des bases de données pour bien les exploiter. Vous utiliserez les différents objets : tables, requêtes, formulaires et états, vous permettant de comprendre leurs rôles et interactions dans Access.'
    Inscription:
      type: object
      required:
        - id
        - code
        - name
      properties:
        id:
          type: string
          description: L'ID d'une inscription, généré automatiquement par Claroline
      # example:
      #   id: 01c292b5-43a4-4c59-9619-33a8309cdbf0
      #   code: ACCESS
      #   name: 'Access : bien débuter avec les bases de données'
      #   plainDescription: 'Pour découvrir Access, comprendre et maîtriser les bases de données relationnelles (BDR) simples.'
