components:
  schemas:
    Course:
      type: object
      required:
        - id
        - code
        - name
      properties:
        id:
          type: string
          description: L'UUID d'une formation, généré automatiquement par Claroline (e.g. 01c292b5-43a4-4c59-9619-33a8309cdbf0)
        code:
          type: string
          description: Le code d'une formation, saisi par le CEP dans Claroline (e.g. ACCESS)
        name:
          type: string
          description: 'Le nom complet de la formation (e.g. Access : bien débuter avec les bases de données)'
        isActive:
          type: boolean
          description: Si la formation est active (true/false)
        creationDate:
          type: string
          description: La date (en ISO) de création de la formation (e.g.)
        typeStage:
          type: string
          description: Le type stage de la formation
        teachingMethod:
          type: string
          description: La méthode d'enseignement de la formation
        codeCategory:
          type: string
          description: Le code catégorie de la formation
        isCertifying:
          type: boolean
          description: Si la formation est certifiante
        isRecurrent:
          type: boolean
          description: Si la formation est cyclique (répétée dans le temps)
        durationHours:
          type: string
          description: La durée en heures de chaque session
        summary:
          type: string
          description: Résumé (description courte) de la formation
        # maxParticipants:
        #   type: string
        #   description: La limite de nombre de participants par session
      example:
        id: '01c292b5-43a4-4c59-9619-33a8309cdbf0'
        code: 'ACCESS'
        name: 'Access : bien débuter avec les bases de données'
        slug: 'access-bien-debuter-avec-les-bases-de-donnees'
        plainDescription: 'Dans cette formation vous découvrirez la construction des bases de données pour bien les exploiter. Vous utiliserez les différents objets: tables, requêtes, formulaires et états, vous permettant de comprendre leurs rôles et interactions dans Access.'
        typeStage: 'Certificat'
        teachingMethod: 'Distanciel'
        codeCategory: 'FSM'
        price: 840
        creationDate: '2021-05-31T14:33:08'
        lastUpdatedDate: '2021-11-22T13:03:05'
        meta:
          tutorRoleName: null
          learnerRoleName: null
          days: 2
          hours: 4
        tags: ['thème # informatique & numérique', 'thème-bis # bases de données & outils de gestion']
    Inscription:
      type: object
      required:
        - id
        - code
        - name
      properties:
        id:
          type: string
          description: L'ID d'une inscription, généré automatiquement par Claroline
      # example:
      #   id: 01c292b5-43a4-4c59-9619-33a8309cdbf0
      #   code: ACCESS
      #   name: 'Access : bien débuter avec les bases de données'
      #   plainDescription: 'Pour découvrir Access, comprendre et maîtriser les bases de données relationnelles (BDR) simples.'
